# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "swagger-ui"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Dell", "Brian Tatnall"]
  s.date = "2013-02-04"
  s.description = "Swagger UI wrapper"
  s.email = "dell.justin@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "examples/index.html.haml",
    "lib/generators/swagger/install/install_generator.rb",
    "lib/swagger.rb",
    "lib/swagger/api.rb",
    "lib/swagger/document.rb",
    "lib/swagger/operation.rb",
    "lib/swagger/version.rb",
    "public/javascripts/swagger.js",
    "public/stylesheets/swagger.css",
    "swagger-ui.gemspec",
    "swagger.gemspec"
  ]
  s.homepage = "http://github.com/justindell/swagger"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Swagger UI"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<actionpack>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<actionpack>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

